# Site settings
title:          Dinkers
description:    "Knowledge share for a group of developers"
# baseurl:        "/tale"
# url:            "https://chesterhow.github.io"

# Author
author:
  name:         Chester How
  url:          https://chester.how
  email:        chesterhow@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  # - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:collections/:title

# Collections
collections:
  python:
    output: true
    description: Everything you need to be useful with the Python programming language.
  dev-ops:
    output: true
    description: Server side stuff
  static-sites:
    output: true
    description: Useful tips, tools, and workflows for creating static websites.
