github: [metadata]
 encoding: UTF-8
 kramdown:
   input: GFM
   hard_wrap: false
 future: true
 jailed: false
 gfm_quirks: paragraph_end

# Site settings
title:          Dinkers
description:    "Knowledge share for a group of developers"
# baseurl:        "/tale"
# url:            "https://chesterhow.github.io"

author:
  name:         Kayra Alat
  url:          https://kayra.co.uk

# Author of tale theme that this site is based on
# author:
#   name:         Chester How
#   url:          https://chester.how
#   email:        chesterhow@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed


# Permalinks
permalink:      /:collections/:title

# Collections
collections:
  python:
    output: true
    description: Everything you need to be useful with the Python programming language.
  dev-ops:
    output: true
    description: Server configuration documentation.
  static-sites:
    output: true
    description: Useful tips, tools, and workflows for creating static websites.
